[package]
name = "malovent-automodder"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
once_cell = "1.21.3"
regex = "1.11.1"
thiserror = "2.0.12"
